# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices.luksroot = {
    device = "/dev/disk/by-uuid/12c76b84-f8e7-44ab-bf84-9a63f2ac80e3"; 
    preLVM = true;
    allowDiscards = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b08c6911-e705-411b-a296-5ad4c38db58b";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/1E88-00B2";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/841c951b-ea86-4a1e-a7a4-fc8196d77457"; }
    ];

}

